wandb_version: 1

Epochs:
  desc: null
  value: 100
Batch size:
  desc: null
  value: 32
Device:
  desc: null
  value: cpu
k-fold:
  desc: null
  value: 10
Dataset:
  desc: null
  value: PROTEINS
learning_rate:
  desc: null
  value: 0.02
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684069354.931571
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 4
      - 5
