wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684245097.932706
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 7
      - 13
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 4
      - 5
    m:
    - 1: WL_iterations
      6:
      - 3
    - 1: WL_Count
      6:
      - 3
