wandb_version: 1

Epochs:
  desc: null
  value: 25
Batch size:
  desc: null
  value: 32
Device:
  desc: null
  value: cpu
k-fold:
  desc: null
  value: 2
Dataset:
  desc: null
  value: PROTEINS
learning_rate:
  desc: null
  value: 0.02
seed:
  desc: null
  value: 42
k_wl:
  desc: null
  value: 3
model:
  desc: null
  value: 1WL+NN:Embedding-Sum
wl_convergence:
  desc: null
  value: false
tags:
  desc: null
  value: []
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684253797.730658
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 1
      - 7
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 4
      - 5
    m:
    - 1: epoch
      6:
      - 3
    - 1: train accuracy
      5: 1
      6:
      - 1
      - 3
      7:
      - 5
    - 1: val accuracy
      5: 1
      6:
      - 1
      - 3
      7:
      - 5
    - 1: train loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 5
    - 1: val loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 5
