#!/bin/bash
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl -1 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 1 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 2 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 3 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 4 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 5 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 6 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 7 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 8 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 9 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 10 --dataset PROTEINS;