#!/bin/bash

python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl -1 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 1 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 2 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 3 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 4 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 5 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 6 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 7 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 8 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 9 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 10 --dataset PROTEINS --wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl -1 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 1 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 2 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 3 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 4 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 5 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 6 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 7 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 8 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 9 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 10 --dataset PROTEINS --no-wl_convergence --tags k-wl_Test;

python Code/main.py --epochs 25 --k_fold 5 --model 1WL+NN:Embedding-Sum --k_wl 3 --dataset ZINC_val --no-wl_convergence --batch_size 128
