#!/bin/bash

python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 6 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 7 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 8 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 9 --dataset PROTEINS;
python Code/main.py --epochs 250 --k_fold 10 --model 1WL+NN:Embedding-Sum --k_wl 10 --dataset PROTEINS;